stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t my-python-app .

test:
  stage: test
  script:
    - python -m unittest discover -s tests

deploy:
  stage: deploy
  script:
    - echo "Deploy stage"
